"""M2: tạo conversations, conversation_messages, test_plans, test_plan_steps

conversation_messages.plan_id ↔ test_plans.source_message_id trỏ vòng vào nhau,
nên FK conversation_messages.plan_id được thêm SAU khi đã tạo đủ 2 bảng.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('owner_id', 'seq_no', name=op.f('uq_conversations_owner_id_seq_no'))
    )
    op.create_index('ix_conversations_sidebar', 'conversations', ['owner_id', sa.literal_column('last_message_at DESC')], unique=False, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_table('conversation_messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('agent', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), server_default='text', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent IN ('planner', 'browser_executor', 'user_simulator', 'evaluator')", name=op.f('ck_conversation_messages_agent_allowed')),
    sa.CheckConstraint("kind IN ('text', 'plan_created', 'plan_updated', 'run_started', 'run_status')", name=op.f('ck_conversation_messages_kind_allowed')),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name=op.f('ck_conversation_messages_role_allowed')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages')),
    sa.UniqueConstraint('conversation_id', 'seq', name=op.f('uq_conversation_messages_conversation_id_seq'))
    )
    op.create_table('test_plans',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_message_id', sa.Text(), nullable=True),
    sa.Column('environment_id', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('preconditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('test_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('llm_provider', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved')", name=op.f('ck_test_plans_status_allowed')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_test_plans_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['conversation_messages.id'], name=op.f('fk_test_plans_source_message_id_conversation_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_plans')),
    sa.UniqueConstraint('conversation_id', 'version', name=op.f('uq_test_plans_conversation_id_version'))
    )
    op.create_table('test_plan_steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('selector', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), server_default='original', nullable=False),
    sa.Column('source_message_id', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('original', 'chat_edit', 'manual')", name=op.f('ck_test_plan_steps_source_allowed')),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plans.id'], name=op.f('fk_test_plan_steps_plan_id_test_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['conversation_messages.id'], name=op.f('fk_test_plan_steps_source_message_id_conversation_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_plan_steps')),
    sa.UniqueConstraint('plan_id', 'step_no', name=op.f('uq_test_plan_steps_plan_id_step_no'))
    )
    op.create_foreign_key(
        op.f('fk_conversation_messages_plan_id_test_plans'),
        'conversation_messages', 'test_plans', ['plan_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_conversation_messages_plan_id_test_plans'), 'conversation_messages', type_='foreignkey')
    op.drop_table('test_plan_steps')
    op.drop_table('test_plans')
    op.drop_table('conversation_messages')
    op.drop_index('ix_conversations_sidebar', table_name='conversations', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_table('conversations')
    # ### end Alembic commands ###
