"""M3: tạo test_runs, test_run_steps, run_interventions

Thêm luôn FK conversation_messages.run_id → test_runs (cột đã có từ 0002, chờ bảng này).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=True),
    sa.Column('test_case_id', sa.Text(), nullable=True),
    sa.Column('rerun_of', sa.Text(), nullable=True),
    sa.Column('environment_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('suite', sa.Text(), server_default='Default', nullable=False),
    sa.Column('environment_name', sa.Text(), nullable=True),
    sa.Column('browser', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('current_step', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'paused', 'waiting_human_input', 'waiting_human_approval', 'completed', 'failed', 'cancelled')", name=op.f('ck_test_runs_status_allowed')),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plans.id'], name=op.f('fk_test_runs_plan_id_test_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rerun_of'], ['test_runs.id'], name=op.f('fk_test_runs_rerun_of_test_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_runs'))
    )
    op.create_index('ix_test_runs_owner_created', 'test_runs', ['owner_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_test_runs_owner_status', 'test_runs', ['owner_id', 'status'], unique=False)
    op.create_index('ix_test_runs_plan', 'test_runs', ['plan_id'], unique=False)
    op.create_table('test_run_steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('selector', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'passed', 'failed', 'skipped')", name=op.f('ck_test_run_steps_status_allowed')),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], name=op.f('fk_test_run_steps_run_id_test_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_run_steps')),
    sa.UniqueConstraint('run_id', 'step_no', name=op.f('uq_test_run_steps_run_id_step_no'))
    )
    op.create_table('run_interventions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('step_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.Text(), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name=op.f('ck_run_interventions_decision_allowed')),
    sa.CheckConstraint("kind IN ('input', 'approval')", name=op.f('ck_run_interventions_kind_allowed')),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], name=op.f('fk_run_interventions_run_id_test_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['test_run_steps.id'], name=op.f('fk_run_interventions_step_id_test_run_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_interventions'))
    )
    op.create_index('ux_run_interventions_open', 'run_interventions', ['run_id'], unique=True, postgresql_where=sa.text('answered_at IS NULL'))
    op.create_foreign_key(
        op.f('fk_conversation_messages_run_id_test_runs'),
        'conversation_messages', 'test_runs', ['run_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_conversation_messages_run_id_test_runs'), 'conversation_messages', type_='foreignkey')
    op.drop_index('ux_run_interventions_open', table_name='run_interventions', postgresql_where=sa.text('answered_at IS NULL'))
    op.drop_table('run_interventions')
    op.drop_table('test_run_steps')
    op.drop_index('ix_test_runs_plan', table_name='test_runs')
    op.drop_index('ix_test_runs_owner_status', table_name='test_runs')
    op.drop_index('ix_test_runs_owner_created', table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ###
