"""M6: tạo evidence_artifacts (bằng chứng từng bước; file lớn nằm ngoài DB, cột storage_key)

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('step_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('network', 'screenshot', 'agent_log', 'console', 'visual_diff')", name=op.f('ck_evidence_artifacts_kind_allowed')),
    sa.CheckConstraint('storage_key IS NOT NULL OR payload IS NOT NULL', name=op.f('ck_evidence_artifacts_has_content')),
    sa.ForeignKeyConstraint(['step_id'], ['test_run_steps.id'], name=op.f('fk_evidence_artifacts_step_id_test_run_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_artifacts'))
    )
    op.create_index('ix_evidence_step', 'evidence_artifacts', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_step', table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    # ### end Alembic commands ###
