"""M7: tạo users, sessions; gắn khoá ngoại owner_id / user_id / answered_by → users

Dữ liệu tạo trước M7 đều thuộc user demo (settings.demo_user_id). Migration tạo sẵn user này
(chưa có mật khẩu → chạy `python -m scripts.create_admin` để đặt), và tạo tài khoản khoá
(không đăng nhập được) cho mọi owner_id lạ còn sót, để gắn khoá ngoại không bị lỗi.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-01
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    # Chủ của dữ liệu cũ. Phải có TRƯỚC khi gắn khoá ngoại bên dưới.
    op.execute(
        "INSERT INTO users (id, username, email, display_name) "
        "VALUES ('USR-DEMO0001', 'admin123', 'admin123@example.com', 'Administrator') "
        "ON CONFLICT (id) DO NOTHING"
    )
    op.execute("""
        INSERT INTO users (id, username, email, display_name)
        SELECT o.id, lower(o.id), lower(o.id) || '@legacy.invalid', 'Legacy owner ' || o.id
        FROM (
            SELECT owner_id AS id FROM conversations UNION SELECT owner_id FROM test_plans
            UNION SELECT owner_id FROM test_runs UNION SELECT answered_by FROM run_interventions
            UNION SELECT user_id FROM feedback
        ) o
        WHERE o.id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM users u WHERE u.id = o.id)
    """)
    op.create_foreign_key(op.f('fk_conversations_owner_id_users'), 'conversations', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_feedback_user_id_users'), 'feedback', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_run_interventions_answered_by_users'), 'run_interventions', 'users', ['answered_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_test_plans_owner_id_users'), 'test_plans', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_test_runs_owner_id_users'), 'test_runs', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_runs_owner_id_users'), 'test_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_test_plans_owner_id_users'), 'test_plans', type_='foreignkey')
    op.drop_constraint(op.f('fk_run_interventions_answered_by_users'), 'run_interventions', type_='foreignkey')
    op.drop_constraint(op.f('fk_feedback_user_id_users'), 'feedback', type_='foreignkey')
    op.drop_constraint(op.f('fk_conversations_owner_id_users'), 'conversations', type_='foreignkey')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
