"""M8: create environments; add FK for execution/test_planning.environment_id

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 01:31:23.262475
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('browser', sa.Text(), nullable=False),
    sa.Column('headless', sa.Boolean(), nullable=False),
    sa.Column('viewport_width', sa.Integer(), nullable=False),
    sa.Column('viewport_height', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=False),
    sa.Column('last_check_status', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("browser IN ('chromium', 'firefox', 'webkit', 'headless_node')", name=op.f('ck_environments_browser_allowed')),
    sa.CheckConstraint("last_check_status IS NULL OR last_check_status IN ('connected', 'error')", name=op.f('ck_environments_last_check_status_allowed')),
    sa.CheckConstraint("llm_provider IN ('google', 'openai', 'anthropic', 'openrouter', 'deepseek', 'azure', 'hub1')", name=op.f('ck_environments_llm_provider_allowed')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_environments_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments')),
    sa.UniqueConstraint('owner_id', 'name', name='owner_name')
    )
    op.create_foreign_key(op.f('fk_conversations_environment_id_environments'), 'conversations', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_test_plans_environment_id_environments'), 'test_plans', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_test_runs_environment_id_environments'), 'test_runs', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_runs_environment_id_environments'), 'test_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_test_plans_environment_id_environments'), 'test_plans', type_='foreignkey')
    op.drop_constraint(op.f('fk_conversations_environment_id_environments'), 'conversations', type_='foreignkey')
    op.drop_table('environments')
    # ### end Alembic commands ###
