"""M10: create test_cases; add FK test_runs.test_case_id

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-01 07:59:43.026578
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('source_plan_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('suite', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_test_cases_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_plan_id'], ['test_plans.id'], name=op.f('fk_test_cases_source_plan_id_test_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_cases'))
    )
    op.create_foreign_key(op.f('fk_test_runs_test_case_id_test_cases'), 'test_runs', 'test_cases', ['test_case_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_runs_test_case_id_test_cases'), 'test_runs', type_='foreignkey')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
