"""M12: create comparisons

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-01 08:22:38.221534
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparisons',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('run_a_id', sa.Text(), nullable=False),
    sa.Column('run_b_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('share_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('run_a_id <> run_b_id', name=op.f('ck_comparisons_different_runs')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_comparisons_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_a_id'], ['test_runs.id'], name=op.f('fk_comparisons_run_a_id_test_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_b_id'], ['test_runs.id'], name=op.f('fk_comparisons_run_b_id_test_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparisons')),
    sa.UniqueConstraint('owner_id', 'run_a_id', 'run_b_id', name='owner_run_pair'),
    sa.UniqueConstraint('share_token', name='comparisons_share_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparisons')
    # ### end Alembic commands ###
